spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC
#        username: root
#        password: 11235813
        url: jdbc:postgresql://localhost:5433/postgres
        username: user
        password: password
    jpa.open-in-view: false

server.port: 8080
